import type { Metadata } from "next";
import { Inter, Source_Serif_4, JetBrains_Mono } from "next/font/google";
import "../globals.css";
import ProviderWrapper from "@/components/providers/provider-wrapper";
import Image from "next/image";

const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontSerif = Source_Serif_4({
  subsets: ["latin"],
  variable: "--font-serif",
});

const fontMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }: LayoutProps<"/">) {
  return (
    <ProviderWrapper>
      <html
        lang="en"
        className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} antialiased`}
      >
        <body className="min-h-svh grid grid-cols-1 lg:grid-cols-2 grid-rows-1">
          <div className="relative h-svh hidden lg:block bg-on-surface">
            <Image
              src={"/images/auth-screen.svg"}
              alt="auth screen side image"
              fill
              loading="eager"
              className="object-contain size-full"
            />
          </div>
          <div className="flex items-center justify-center">{children}</div>
        </body>
      </html>
    </ProviderWrapper>
  );
}
