import Sidebar from "@/components/ui/dashboard/sidebar";
import { seoConfig } from "@/constants/meta-info";
import { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: {
    default: seoConfig.dashboardPages.overview.title,
    template: "%s | NextBio",
  },
  description: "Generated by create next app",
};
const DashboardLayout = ({ children }: { children: ReactNode }) => {
  return (
    <>
      {/* <div className="grid grid-cols-6 md:grid-cols-12 grid-rows-1"> */}
        {/* <Sidebar /> */}
        <main className="overflow-y-auto bg-surface dark:bg-background w-full py-4 ">
          {children}
        </main>
      {/* </div>   */}
    </>
  );
};

export default DashboardLayout;
