import type { Metadata } from "next";
import { Inter, Source_Serif_4, JetBrains_Mono } from "next/font/google";
import "../globals.css";
import ProviderWrapper from "@/components/providers/provider-wrapper";
import Navbar from "@/components/ui/layout/navbar";
import Footer from "@/components/ui/layout/footer";

const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontSerif = Source_Serif_4({
  subsets: ["latin"],
  variable: "--font-serif",
});

const fontMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <ProviderWrapper>
      <html
        lang="en"
        className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} antialiased`}
      >
        <body className="min-h-full flex flex-col text-on-surface bg-surface antialiased">
          {/* <Navbar /> */}
          <main className="flex-1 ml-0 md:ml-60 h-full overflow-y-auto bg-[#F8FAFC] dark:bg-background p-gutter md:p-lg w-full max-w-container-max mx-auto">
            {children}
          </main>
          <Footer/>
        </body>
      </html>
    </ProviderWrapper>
  );
}
